# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sweatplot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='patient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sweatplot_app.Patient'),
            preserve_default=False,
        ),
    ]
