# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweatplot_app', '0002_session_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='diagnosis',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('1', 'Female'), ('2', 'Male'), ('3', 'Other')], default='Female', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='data',
            field=models.CharField(default='', max_length=300, verbose_name='full path to csv'),
            preserve_default=False,
        ),
    ]
