# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweatplot_app', '0004_auto_20160831_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='csv_path',
            new_name='csv',
        ),
        migrations.AlterField(
            model_name='session',
            name='phase_bands',
            field=models.CharField(default='0.00, 0.313, 0.615, 0.917, 1.211, 1.505, 1.800, 2.093', max_length=200, verbose_name='phase_bands'),
        ),
    ]
