# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweatplot_app', '0005_auto_20160901_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='csv',
            field=models.FileField(max_length=200, upload_to='', verbose_name='full path to csv'),
        ),
    ]
